Feature/feed
estartando-devs/Busquepet pull request #33
Opened 2020-12-12 01:32 UTC by yagovaluchedevs

Concluindo a tela do Feed. Sem funcionalidade!!

2020-12-12 01:42 UTC, pietra-nunes approved these changes

2020-12-12 19:28 UTC, Mooooooov requested changes

2020-12-12 19:28 UTC, Mooooooov commented on src/components/HeaderFeed/styles.scss
> +		width: 25%;
Alguma dessas condições não está posibilitando o title "BUSQUEPET" centralizar ao meio e o icone ir para o final da página.

![image](https://user-images.githubusercontent.com/49696764/101993119-c0a91700-3c96-11eb-8421-59b799d5aec6.png)

2020-12-13 17:30 UTC, Mooooooov approved these changes

2020-12-13 17:30 UTC, merged