Feature/InputField
estartando-devs/Busquepet pull request #4
Opened 2020-12-01 01:23 UTC by evertoont

2020-12-01 20:50 UTC, Brenont requested changes

2020-12-01 20:50 UTC, Brenont commented on src/App.js
> +import {InputField} from './components/InputField'
Esses componentes estão sendo importados mas não são utilizados, o react mesmo avisa no console sobre em uma mensagem de warning.
Isso está causando um problema pois o deploy não é feito com warnings.

2020-12-01 21:24 UTC, jonataspinto commented on src/components/InputField/style.scss
> +@import url("https://fonts.googleapis.com/css2?family=Jost:wght@400;500&display=swap");
@evertoont  essa fonte será usada apenas nesse input?

2020-12-01 21:31 UTC, evertoont commented on src/App.js
> +import {InputField} from './components/InputField'
Acabei me passando e esqueci de remover os imports. Irei corrigir

2020-12-01 21:31 UTC, evertoont commented on src/components/InputField/style.scss
> +@import url("https://fonts.googleapis.com/css2?family=Jost:wght@400;500&display=swap");
A fonte era apenas um teste que esqueci de retirar. Irei corrigir

2020-12-02 00:48 UTC, Brenont approved these changes

2020-12-02 00:48 UTC, merged