Ajustando bugs de texto e afins
estartando-devs/Busquepet pull request #63
Opened 2020-12-17 03:16 UTC by pietra-nunes

Falta resolver a cor de dois dos títulos do cadastro do adotante.

2020-12-17 21:33 UTC, yagovaluchedevs commented on src/pages/cadastro-do-doador/register-person/adopter-registration/steps/register-adopter-data/index.jsx
> +      <section className="contacte-forme">
acredito que tenha escrito errado, não seria contact-form?

2020-12-17 21:33 UTC, yagovaluchedevs commented on src/pages/cadastro-do-doador/register-person/register-donor/steps/donor-person-data/styles.scss
> +.contentforme {
não seria content-form  ?

2020-12-18 00:05 UTC, pietra-nunes commented on src/pages/cadastro-do-doador/register-person/adopter-registration/steps/register-adopter-data/index.jsx
> +      <section className="contacte-forme">
tava tentando alterar o nome pra nao puxar o sass de outro titulo, que nem tava acontecendo

2020-12-18 19:27 UTC, yagovaluchedevs requested changes

2020-12-18 19:27 UTC, yagovaluchedevs commented on src/pages/cadastro-do-doador/register-person/adopter-registration/steps/register-adopter-data/index.jsx
> +      <div className="testando">
esqueceu de alterar p nome dessa classe

2020-12-19 04:23 UTC, closed without merging